package com.ym.game.plugin.google.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ym.game.plugin.google.dao.LocalPurchaseBean;

import com.ym.game.plugin.google.dao.LocalPurchaseBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localPurchaseBeanDaoConfig;

    private final LocalPurchaseBeanDao localPurchaseBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localPurchaseBeanDaoConfig = daoConfigMap.get(LocalPurchaseBeanDao.class).clone();
        localPurchaseBeanDaoConfig.initIdentityScope(type);

        localPurchaseBeanDao = new LocalPurchaseBeanDao(localPurchaseBeanDaoConfig, this);

        registerDao(LocalPurchaseBean.class, localPurchaseBeanDao);
    }
    
    public void clear() {
        localPurchaseBeanDaoConfig.clearIdentityScope();
    }

    public LocalPurchaseBeanDao getLocalPurchaseBeanDao() {
        return localPurchaseBeanDao;
    }

}
